ON/OFF/ON_READY
Gaucho-Racing/VCU pull request #2
Opened 2023-03-03 05:00 UTC by yarwinliu

first pull request

2023-03-12 02:58 UTC, Th3will requested changes
There's some stuff to look at before merging other than that good work

2023-03-12 02:58 UTC, Th3will commented on src/main.cpp
> +enum States = {ERROR, OFF, ON, ON_READY, DRIVE, CHARGE_PRECHARGE, CHARGE_CHARGING, CHARGE_FULL};
I'm like 90% sure this is an illegal way to declare an enum.
It should be 
`enum States {ERROR, OFF, ON, ON_READY, DRIVE, CHARGE_PRECHARGE, CHARGE_CHARGING, CHARGE_FULL}`
We should've changed in main but merging it should fix it.
We should also have this declared in some header file so all other files can access it

2023-03-12 02:58 UTC, Th3will commented on src/on.cpp
> +States ON() {
Can't access States as it's an enum and also not declared anywhere here. Might be better to declare it as a function

2023-03-12 02:58 UTC, Th3will commented on src/on_ready.cpp
> +States ON_READY() {
see above

2023-03-12 02:58 UTC, Th3will commented on src/onOffUtility.cpp
> +    //TODO - insert acutal code
Not really sure what the point of returning different values if the return type is bool

2023-03-12 02:58 UTC, Th3will commented on src/onOffUtility.cpp
> +    //TODO - insert acutal code
Is it supposed to be returning an int?

2023-03-12 02:58 UTC, Th3will commented on src/onOffUtility.cpp
> +   if (!Inverter.getDriveEnable() != 1) return 15;
redundant w/ line 31?

2023-03-12 02:58 UTC, Th3will commented on src/onOffUtility.cpp
> +   if (Battery.getCurrent() > -500) return 24;
I'm a little confused here, how exactly does measuring the current work. Is it supposed to negative current indicating draw from the battery? If so shouldn't it be get current is less than -500?

2023-03-12 02:58 UTC, Th3will commented on src/off.cpp
> +States OFF() {
See below (I didn't see this file b4 writing that sry)

2023-03-12 02:58 UTC, Th3will commented on src/on.cpp
> +using namespace std;
it's better practice to omit this

2023-03-12 02:58 UTC, Th3will commented on src/on.cpp
> +#include <iostream>
I don't think the teensy can use cout but rather it utilizes Serial for printing things so this might be useless

2023-03-12 19:32 UTC, Th3will commented on src/main.cpp
> +enum States = {ERROR, OFF, ON, ON_READY, DRIVE, CHARGE_PRECHARGE, CHARGE_CHARGING, CHARGE_FULL};
If u try to build it will throw an error

2023-03-12 19:36 UTC, Th3will commented on src/onOffUtility.cpp
> +   if (!Inverter.getDriveEnable() != 1) return 15;
oops missed missed the !

2023-03-12 19:37 UTC, Th3will commented on src/onOffUtility.cpp
> +   if (!Inverter.getDriveEnable() != 1) return 15;
Still confused tho since line 31 is `if (Inverter.getDriveEnable() != 1) return 13;` where as this line is checking for the opposite?, won't that always return an error?

2023-03-12 19:37 UTC, Th3will commented on src/onOffUtility.cpp
> +   if (Battery.getCurrent() > -500) return 24;
kk

2023-03-12 19:39 UTC, Th3will commented on src/main.cpp
> +enum States = {ERROR, OFF, ON, ON_READY, DRIVE, CHARGE_PRECHARGE, CHARGE_CHARGING, CHARGE_FULL};
see https://en.cppreference.com/w/cpp/language/enum

2023-04-14 03:08 UTC, nikunjparasar approved these changes

2023-04-14 03:08 UTC, nikunjparasar commented
merge to main

2023-04-14 03:09 UTC, nikunjparasar approved these changes
merge to main

2023-04-14 03:12 UTC, Th3will approved these changes

2023-04-14 03:13 UTC, merged